#!/bin/bash

black(){
        echo -en "\x1B[30m$1\x1B[0m"
        [[ -z "${2}" ]] || echo -en "\x1B[30m$($2) \x1B[0m"
}
red(){
        echo -en "\x1B[31m$1\x1B[0m"
         [[ -z "${2}" ]] || echo -en "\x1B[31m$($2) \x1B[0m"
}
green(){
        echo -en "\x1B[32m$1\x1B[0m"
        [[ -z "${2}" ]] || echo -en "\x1B[32m$($2) \x1B[0m"
}
yellow(){
        echo -en "\x1B[33m$1\x1B[0m"
        [[ -z "${2}" ]] || echo -en "\x1B[33m$($2) \x1B[0m"
}
blue(){
        echo -en "\x1B[34m$1\x1B[0m"
        [[ -z "${2}" ]] || echo -en "\x1B[34m$($2) \x1B[0m"
}
purple(){
        echo -en "\x1B[35m$1\x1B[0m"
        [[ -z "${2}" ]] || echo -en "\x1B[35m$($2) \x1B[0m"
}
cyan(){
        echo -en "\x1B[36m$1\x1B[0m"
        [[ -z "${2}" ]] || echo -en "\x1B[36m$($2) \x1B[0m"
}
white(){
        echo -en "\x1B[37m$1\x1B[0m"
        [[ -z "${2}" ]] || echo -en "\x1B[33m$($2) \x1B[0m"
}

if [ -z "$1" ]; then
    echo "Usage:     colorize [COLOR] [MESSAGE] ?[COMMAND] ?n "
    echo "Colors:    white | cyan | purple | blue | yellow | black | red | green"
    echo "NOTE:      if the thirth or fourth argument is n, put a newline"
else
    [[ "$2" == "" ]] && [[ "$4" == "n" ]] && "$1" "\0" "$3" && echo && exit
    [[ "$2" == "" ]] && [[ ! "$4" == "n" ]] && "$1" "\0" "$3" && exit
    [[ "$4" == "n" ]] && "$1" "$2\n" "$3" && echo && exit
    [[ "$3" == "n" ]] && "$1" "$2" && echo && exit
    [[ -n "$3" ]] && "$1" "$2\n" "$3" && exit
    "$1" "$2" "$3"
fi
exit

