#!/bin/sh

dunstify -a "playlistopen" -r 5666 -i "music" -u low "While Study" "Select a playlist to listen while you study"

SELECT=$(find "$HOME/docs/study/while-study/" -name "*.webm" | dmenu -i -c -l 30 -p "Playlists" -cw 300)

if [ -n "$SELECT" ]; then
    VID=${SELECT##*/}
    VID=${VID%[*}
    dunstify -a "playlistopen" -r 5666 -i "music" -u low "While Study" "You have chosen: \n $VID"
    mpv "$SELECT"
else
    dunstify -a "playlistopen" -r 5666 -u normal "While Study" "You haven't chosen anything to listen to."
fi

exit
