#!/bin/bash

dunstify -a "playlistopen" -r 5666 -i "music" -u low "While Study" "Select a playlist to listen while you study"

SELECT=$(find "$HOME/docs/study/while-study/" -type f \( -name "*.webm" -o -name "*.mkv" \))

# Function to trim pathway string
MakeNameOnly() {
    local line="$1"
    modified=${line##*/}
    modified=${modified%[*}
    echo "$modified"
}

FILES_ONLY=""

# Process each line
while IFS= read -r line; do
    modified_line=$(MakeNameOnly "$line")
    # append the modified lines
    FILES_ONLY="${FILES_ONLY}${modified_line}"$'\n'
done <<< "$SELECT"

# Select from the files
SELECT=$(echo "$FILES_ONLY" | dmenu -i -c -l 30 -p "Playlists" -cw 300)

if [ -n "$SELECT" ]; then
    # Modify `select` variable to have its full pathname
    SELECT=$(find "$HOME/docs/study/while-study/" -type f \( -name "*.webm" -o -name "*.mkv" \) | grep "$SELECT" )
    # Trim again
    VID=$(MakeNameOnly "$SELECT")
    dunstify -a "playlistopen" -r 5666 -i "music" -u low "While Study" "You have chosen: \n $VID"
    # Open file in mpv
    mpv "$SELECT"
else
    dunstify -a "playlistopen" -r 5666 -u normal "While Study" "You haven't chosen anything to listen to."
fi

exit

